[build]
  publish = "dist"
  command = "astro build"

[[headers]]
  for = "/*"
  [headers.values]
  Content-Type = "text/html; charset=utf-8"

# Optionnel : redirection vers index.html (utile pour les routes client-side)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
